version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../:/app:delegated
      - ./nginx/logs:/var/log/nginx
    networks:
      - default
    links:
      - php
  php:
    build:
      context: php
      dockerfile: php.Dockerfile
    links:
      - mysql
    volumes:
      - ./../:/app
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    networks:
      - default