version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ${DOCKER_CONTAINER_NGINX}
    ports:
      - "${DOCKER_CONTAINER_NGINX_PORT_80}:80"
      - "${DOCKER_CONTAINER_NGINX_PORT_433}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www:delegated
      - ./nginx/logs:/var/log/nginx
    networks:
      - default
    links:
      - ${DOCKER_CONTAINER_PHP}
  php:
    container_name: ${DOCKER_CONTAINER_PHP}
    build:
      context: php
      dockerfile: php.Dockerfile
    links:
      - ${DOCKER_CONTAINER_MYSQL}
    volumes:
      - ./../:/var/www
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: ${DOCKER_CONTAINER_MYSQL}
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    networks:
      - default